### ISSUE TITLE
Logs showing up as `Error` instead of `Info`

### ISSUE THREAD

**Issue by miketheman** [l0k0ms/log-workshop#4]
From this step:
https://github.com/l0k0ms/log-workshop/tree/master/workshop/exercise_1#adding-new-application-logs

I uncommented these lines:
https://github.com/l0k0ms/log-workshop/blob/a4b1942ee91dc732a1ee360fc53d0e5c4a9fd69a/workshop/exercise_1/app/thinker.py#L33-L34

And the resulting log lines show up in the interface as `Error`:

<img width="890" alt="screen shot 2018-07-11 at 2 32 46 pm" src="https://user-images.githubusercontent.com/529516/42592380-507b7998-8517-11e8-9122-7dbae7df3f19.png">

My expectation is that the log level be preserved.

**Comment by NilsBunge** [comment]
Hello @miketheman,

So by default on container environment, the agent uses `Info` for Stdout and `Error` for Stderr.
I assume that Redis is logging on Stderr which is why you see Error by default.

If you are interested to learn more about the status remapping, you can find more information in our article on this subject: https://docs.datadoghq.com/logs/faq/why-do-my-logs-show-up-with-an-info-status-even-for-warnings-or-errors/

**Comment by miketheman** [comment]
Hey @NBParis !

Thanks for checking - the logger here is the Python logger, not the redis one - as noted with `aiohttp_logger.info` - which should be emitting a log level of `INFO`.

**Comment by NilsBunge** [comment]
Would it be possible to have a screenshot of the Log contextual panel (just click on any log) just to see what the JSON look like?

**Comment by miketheman** [comment]
Unfortunately, no - I was using a demo workshop Datadog account and left the access details on the desk for the next attendee. It should be reproducible by running the exercise 1 from this workshop.

**Comment by NilsBunge** [comment]
Understood. Will do and let you know.
